import os
import asyncio
from dotenv import load_dotenv
import telegram
from datetime import datetime

load_dotenv()

TOKEN   = os.getenv("TELEGRAM_TOKEN")
CHAT_ID = os.getenv("TELEGRAM_CHAT_ID")

async def send_message(text: str):
    bot = telegram.Bot(token=TOKEN)
    await bot.send_message(
        chat_id=CHAT_ID,
        text=text,
        parse_mode="HTML"
    )

async def send_fraud_alert(anomalies: list, mean: float):
    now = datetime.now().strftime("%d/%m/%Y %H:%M")
    
    message = f"""
🚨 <b>FRAUD ALERT — {now}</b>

📊 Phát hiện <b>{len(anomalies)} anomaly</b> trong dữ liệu giao dịch

"""
    for a in anomalies:
        message += f"""
⚠️ <b>Giờ {int(a['hour']):02d}:00</b>
   Fraud rate: <b>{a['fraud_rate']}%</b>
   Z-score: {round(a['z_score'], 2)}
   Cao hơn TB: {round(a['fraud_rate']/mean, 1)}x
"""

    message += f"""
━━━━━━━━━━━━━━━━━━
🤖 Auto-generated by Finance Analytics Bot
"""
    
    await send_message(message)
    print("✅ Đã gửi alert lên Telegram!")

async def send_insight(insight_text: str):
    now = datetime.now().strftime("%d/%m/%Y %H:%M")
    
    message = f"""
📈 <b>AI INSIGHT REPORT — {now}</b>

{insight_text[:3000]}

━━━━━━━━━━━━━━━━━━
🤖 Auto-generated by Finance Analytics Bot
"""
    await send_message(message)
    print("✅ Đã gửi insight lên Telegram!")

if __name__ == "__main__":
    # Test gửi tin nhắn
    async def test():
        await send_message("✅ Finance Analytics Bot đã kết nối thành công!")
    
    asyncio.run(test())